### ISSUE TITLE
Model wigths

### ISSUE THREAD

**Issue by AzazelHD** [mani2106/pokemon-classifier#3]
Hi dude,

Could you share the weights of the model?

It isnt completed and i would like to do fine-tune on it

**Comment by mani2106** [comment]
Sorry for the delay, I am not watching this since this is an old project, I don't remember the exact weights file I used to deploy the app, but [here](https://drive.google.com/file/d/1-JBCdUPQpvb91fm4WG6aWAu5gaV-NB24/view?usp=sharing) is another version of the same, keep in mind that this is a fastai model

**Comment by hershey-harsh** [comment]
Do you have a new Gen 8 model?

**Comment by mani2106** [comment]
> Do you have a new Gen 8 model?

No, the dataset I used to build the model probably had some description saying there were only images up till the 7th gen.
Unfortunately the dataset is not available in kaggle.

**Comment by hershey-harsh** [comment]
Do you have discord by any chance? I want to talk about this in-depth
My discord: Future#0811
My email: Futureslinky369@gmail.com
Or is there a way I can contact you privately? Thank you very much!
